# Generated by Django 5.0.2 on 2025-03-19 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vectorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Filename')),
                ('credits_used', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Credits Used')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='Status')),
                ('result_url', models.URLField(blank=True, verbose_name='Result URL')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vectorizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vectorization',
                'verbose_name_plural': 'Vectorizations',
                'ordering': ['-created_at'],
            },
        ),
    ]
